[package]
name = "raytracing-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.30.8"
image = "0.25.8"
rand = "0.9.2"
rayon = "1.11.0"
sobol_burley = "0.5.0"
softbuffer = "0.4.6"
winit = "0.30.12"
